### ISSUE TITLE
Develop solution to image hosting problem

### ISSUE THREAD

**Issue by avkoehl** [ucdavisdatalab/adventures_in_data_science#1]
problem
===
Contributors such as @carriesalex don't have access to upload to the ds server. This makes it hard to embed images in the course reader.

task
===
brainstorm solutions, pick the best one.

**Comment by avkoehl** [comment]
One option is to link directly to the file hosted by github user content. e.g https://raw.githubusercontent.com/ucdavisdatalab/adventures_in_data_science/master/img/141-1418284_cloud-server-clipart-transparent-cloud-server-icon-transparent.png

**Comment by avkoehl** [comment]
Another option. Move the images directory into docs/ and then have relative path links in the html

**Comment by avkoehl** [comment]
Looking closer, it seems that the html has the images embedded as base64 strings. Which if I understand correctly is a string that contains the data of the binary image itself. This means the image just needs to be present when the R is rendering the Rmarkdown. As a result, in the Rmarkdown, images can just be relative paths to the img directory, and the images don't need to be hosted on ds.

will test this.

**Comment by avkoehl** [comment]
> Looking closer, it seems that the html has the images embedded as base64 strings. Which if I understand correctly is a string that contains the data of the binary image itself. This means the image just needs to be present when the R is rendering the Rmarkdown. As a result, in the Rmarkdown, images can just be relative paths to the img directory, and the images don't need to be hosted on ds.
> 
> will test this.

This worked and seems the most intuitive. I think future edits to the course reader should just have relative links to the image, and the image saved in the img directory.  @nick-ulle @t-shoemaker Thoughts?

**Comment by t-shoemaker** [comment]
That seems fine on my end. I agree that it's probably the easiest way to manage everything.
