### ISSUE TITLE
Rendering problem in ch 12 (data structures)

### ISSUE THREAD

**Issue by wes-brooks** [ucdavisdatalab/adventures_in_data_science#10]
The square bracket in this sentence has been causing RMarkdown problems for @liza-wood :
>    Note the use of the "[" character to indicated repeated elements in the data:

It gets interpreted as the start of a block that interferes with rendering everything hat comes after. Liza says that quoting it with backticks rather than double-quotes solved the problem for her. This was apparently not a problem for @t-shoemaker, who built the version that's on the website. I think we need to figure out what platforms are handling that character differently.

**Comment by nick-ulle** [comment]
We should probably be quoting code in backticks anyway...

**Comment by t-shoemaker** [comment]
See #11, where @nick-ulle's comment about backticks is worked into a longer TODO list.
