### ISSUE TITLE
Fix Caching for Lesson 13

### ISSUE THREAD

**Issue by nick-ulle** [ucdavisdatalab/adventures_in_data_science#6]
RMarkdown's caching mechanism doesn't work well with xml2 objects, so caching code chunks in lesson 13 causes knitting the book to fail. On the other hand, we should probably cache the chunks in lesson 13 that download data from the web, so that we aren't downloading data every time we knit.

This issue is a reminder to myself to look into a workaround.

**Comment by t-shoemaker** [comment]
What if we just cached the HTML and used dummy code to demonstrate what it would look like to actually scrape for students? (We could even run the process on the cached HTML and just keep that code block hidden on the reader)

**Comment by nick-ulle** [comment]
Yeah, that's what I was thinking too. I'll add some hidden code chunks to load the data from cached HTML files instead of the web.

**Comment by nick-ulle** [comment]
Fixed by commit efe4ca0.
