### ISSUE TITLE
Generate a requirements file for the whole site

### ISSUE THREAD

**Issue by t-shoemaker** [ucdavisdatalab/adventures_in_data_science#8]

**Comment by nick-ulle** [comment]
We might want to use [Packrat](https://rstudio.github.io/packrat/) with/for this.

**Comment by nick-ulle** [comment]
Here's a shell command (using [ripgrep](https://github.com/BurntSushi/ripgrep)) that gets all packages loaded with `library`:
```sh
rg 'library ?\([^)]+' --no-heading -INo | cut -d'(' -f2 | sort | uniq
```

**Comment by t-shoemaker** [comment]
Will close this for now, since the immediate task of generating a list of libraries is done, but we can reopen after Nick is done investigating renv.
